# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBNGSYILWEN1wv7C3Mjw7jyC7Zr0a5o2
"""

!pip install ultralytics opencv-python torch torchvision torchaudio

import cv2

cap = cv2.VideoCapture("/content/input_video.mp4")
print("Video opened:", cap.isOpened())
print("FPS:", cap.get(cv2.CAP_PROP_FPS))
print("Frames:", cap.get(cv2.CAP_PROP_FRAME_COUNT))
cap.release()

!pip install ultralytics opencv-python

from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # lightweight & fast

import cv2
import time

video_path = "/content/input_video.mp4"
cap = cv2.VideoCapture(video_path)

person_threshold = 5   # crowd condition
fps_list = []

while cap.isOpened():
    start = time.time()
    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame)[0]
    person_count = 0

    for box in results.boxes:
        cls = int(box.cls[0])
        if cls == 0:  # person
            person_count += 1

    if person_count >= person_threshold:
        cv2.putText(frame, "Crowded Scene Detected", (20,40),
                    cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)

    end = time.time()
    fps_list.append(1/(end-start))

cap.release()
print("Average FPS (Before Optimization):", sum(fps_list)/len(fps_list))

import torch

quantized_model = torch.quantization.quantize_dynamic(
    model.model,
    {torch.nn.Linear},
    dtype=torch.qint8
)

torch.save(quantized_model.state_dict(), "optimized_model.pt")
print("Optimized model saved!")

fps_list_opt = []
cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    start = time.time()
    ret, frame = cap.read()
    if not ret:
        break

    _ = model(frame)
    end = time.time()
    fps_list_opt.append(1/(end-start))

cap.release()
print("Average FPS (After Optimization):", sum(fps_list_opt)/len(fps_list_opt))

import torch
from ultralytics import YOLO
import os

model = YOLO("yolov8n.pt")

quantized_model = torch.quantization.quantize_dynamic(
    model.model,
    {torch.nn.Linear},
    dtype=torch.qint8
)

# Save explicitly to /content (Colab visible folder)
save_path = "/content/optimized_model.pt"
torch.save(quantized_model.state_dict(), save_path)

print("Saved at:", save_path)
print("Files in /content:", os.listdir("/content"))

